import WorkspaceUsers from "../../components/domain/WorkspaceUsers/WorkspaceUsers";

const ScriptResources = {
    Page404: '404 - Page Not Found',
    PageDoNotExist: 'The page you are looking for does not exist.',
    PageGoToHome: 'Go to Home',
    IndexHeader: 'Welcome to Our Application',
    IndexParagraph: 'Navigate to the Demo Form to get started!',
    TotalItems: 'Total Items:',
    ItemsPerPage: 'Items per page:',
    ErrorFetchingWorkspaces: 'Error fetching workspaces',
    CreateNew: 'Create New',
    Workspaces: 'Workspaces',
    WorkspaceId: 'Workspace ID',
    WorkspaceName: 'Workspace Name',
    CreatedBy: 'Created By',
    CreatedAt: 'Created At',
    LoadingOrLogin: 'Loading... or please log in to view your data.',
    SomethingWentWrong: 'Something went wrong',
    SomethingWentWrongDescription: 'We encountered an unexpected error while processing your request. Please try again or check back later.',
    SomethingWentWrongRetry: 'Try Again',
    SomethingWentWrongGoHome: 'Go Home',
    SomethingWentWrongContactSupport: 'If the problem persists, please contact support.',
    Loading: 'Loading...',
    PleaseWait: 'Please wait while we load the data.',
    LoadingTakeLonger: 'If this takes longer than expected, please check your internet connection or try refreshing the page.',
    Cancel: 'Cancel',
    Create: 'Create',
    DeleteConfirmation: 'Are you sure you want to delete this item?',
    WorkspaceDeleted: 'Workspace deleted successfully.',
    ErrorDeletingWorkspace: 'Error deleting workspace',
    EditWorkspace: 'Edit Workspace',
    Save: 'Save',
    ErrorUpdatingWorkspace: 'Error updating workspace',
    OptimisticLockingUserChoice: 'This entity has been modified by someone else. Would you like to overwrite their changes?\n\n' + '• Click \'OK\' to overwrite with your changes\n' + '• Click \'Cancel\' to refresh and see the latest version',
    EditTask: 'Edit Task',
    Name: 'Name',
    EnterTaskName: 'Enter task name',
    EnterDescription: 'Enter description',
    Description: 'Description',
    DueDate: 'Due Date',
    Estimate: 'Estimate',
    Type: 'Type',
    Priority: 'Priority',
    Close: 'Close',
    AddNewTaskName: 'Add New Task Name...',
    Add: 'Add',
    AddCard: 'Add Card',
    DoubleClickToSeeAllTasks: 'Double click on workspace to see all tasks',
    Email: 'Email',
    Actions: 'Actions',
    WorkspaceUsers: 'Workspace {0} Users',
    ErrorFetchingWorkspacesUsers: 'Error fetching workspaces users',
    CannotBeEmpty: 'cannot be empty',
    InvalidEmailFormat: 'Invalid email format',
}

export default ScriptResources;